#!/bin/sh

set -e

destdir=$1

for d in openssl $destdir; do
    if [ -e $d ]; then
        rm -rf $d
    fi
done

# build openssl
mkdir openssl
curl -L https://www.openssl.org/source/openssl-1.1.1f.tar.gz | tar xz -C openssl --strip-components 1
cd openssl
./config --prefix=$destdir no-dtls no-shared no-ssl no-tests no-tls
make
make install_sw
